[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.3"

# Redirects for broken links in blog posts
[[redirects]]
  from = "/guides/relocation/zurich-vs-zug-comparison/*"
  to = "/blog/zurich-vs-zug-choosing-ideal-swiss-relocation-destination/"
  status = 301
  force = true

[[redirects]]
  from = "/guides/relocation/zurich-relocation-costs/*"
  to = "/blog/hidden-costs-zurich-relocation-budget-planning-expats/"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/free-consultation"
  status = 301
  force = true

# Healthcare providers redirects with proper canonical handling
[[redirects]]
  from = "/healthcare/all-insurances/kpt"
  to = "/healthcare/all-insurances/kpt/"
  status = 301
  force = true

[[redirects]]
  from = "/healthcare/all-insurances/sanitas"
  to = "/healthcare/all-insurances/sanitas/"
  status = 301
  force = true

# Prevent Astro 404 handling issues
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=86400"