[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.3"

# NEW REDIRECTS FOR RECENT SEO OPTIMIZATION CHANGES

# Redirect old "expats" blog post to new renamed version
[[redirects]]
  from = "/blog/best-health-insurance-switzerland-expats"
  to = "/blog/best-health-insurance-switzerland"
  status = 301
  force = true

[[redirects]]
  from = "/blog/best-health-insurance-switzerland-expats/"
  to = "/blog/best-health-insurance-switzerland"
  status = 301
  force = true

# Redirect deleted regional guides to working alternatives
[[redirects]]
  from = "/guides/how-to/find-health-insurance-zurich"
  to = "/guides/how-to/find-best-health-insurance"
  status = 301
  force = true

[[redirects]]
  from = "/guides/how-to/find-health-insurance-zurich/"
  to = "/guides/how-to/find-best-health-insurance"
  status = 301
  force = true

[[redirects]]
  from = "/guides/how-to/change-health-insurance-zurich"
  to = "/guides/how-to/change-health-insurance"
  status = 301
  force = true

[[redirects]]
  from = "/guides/how-to/change-health-insurance-zurich/"
  to = "/guides/how-to/change-health-insurance"
  status = 301
  force = true

[[redirects]]
  from = "/guides/how-to/save-health-insurance-geneva"
  to = "/guides/how-to/choose-health-insurance-deductible"
  status = 301
  force = true

[[redirects]]
  from = "/guides/how-to/save-health-insurance-geneva/"
  to = "/guides/how-to/choose-health-insurance-deductible"
  status = 301
  force = true

[[redirects]]
  from = "/guides/how-to/save-health-insurance-basel"
  to = "/guides/how-to/choose-health-insurance-deductible"
  status = 301
  force = true

[[redirects]]
  from = "/guides/how-to/save-health-insurance-basel/"
  to = "/guides/how-to/choose-health-insurance-deductible"
  status = 301
  force = true

# EXISTING REDIRECTS (keeping all previous ones)

# Redirects for broken links in blog posts
[[redirects]]
  from = "/news/switching-health-insurance-in-switzerland"
  to = "/healthcare/switching-health-insurance"
  status = 301
  force = true

[[redirects]]
  from = "/guides/relocation/zurich-vs-zug-comparison/*"
  to = "/blog/zurich-vs-zug-choosing-ideal-swiss-relocation-destination/"
  status = 301
  force = true

[[redirects]]
  from = "/guides/relocation/zurich-relocation-costs/*"
  to = "/blog/hidden-costs-zurich-relocation-budget-planning-expats/"
  status = 301
  force = true

[[redirects]]
  from = "/news/gyms-in-switzerland"
  to = "/guides/how-to/gym-coverage-health-insurance"
  status = 301
  force = true

# Healthcare providers redirects with proper canonical handling
[[redirects]]
  from = "/healthcare/all-insurances/kpt"
  to = "/healthcare/all-insurances/kpt/"
  status = 301
  force = true

[[redirects]]
  from = "/healthcare/all-insurances/sanitas"
  to = "/healthcare/all-insurances/sanitas/"
  status = 301
  force = true

# Prevent Astro 404 handling issues
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=86400"