app = "expat-savvy-api"
primary_region = "fra"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8000"
  PLAUSIBLE_DOMAIN = "expat-savvy.ch"
  SUPABASE_URL = "https://gwvfppnwmlggjofdfzdu.supabase.co"

[deploy]
  # No release command needed for Supabase
  # release_command = "python init_db.py"